name: your-service

services:
  service_name:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - .:/proj_base_path
    command: sleep infinity
