name: your-service

services:
  service_name:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - .:/proj_base_path
    command: sleep infinity
  jupyter_notebook:
    build:
      context: .
      dockerfile: Dockerfile-jupyter
    ports:
      - "8899:8888"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - .:/proj_base_path
