FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Adding path to system environment variable
ENV BASEPATH="/app"
ENV PYTHONPATH="$PYTHONPATH:$BASEPATH"

# Install Git & MySQL Client
RUN apt-get update \
  && apt-get install -y --no-install-recommends git default-mysql-client \
  && apt-get purge -y --auto-remove \
  && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements.txt requirements.txt
# COPY . .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir notebook==7.2.2

WORKDIR /app

# Make port 8888 available to the world outside the container
EXPOSE 8888

# Run Jupyter Notebook when the container launches
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--IdentityProvider.token=''", "--ServerApp.password=''"]
