[project]
name = "rough-work-20xxyyzz"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy==2.1.2",
    "pandas==2.2.3",
    "scikit-learn==1.5.2",
]
